//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankmanagementmainapplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int user_id { get; set; }
        public string emp_name { get; set; }
        public string gender { get; set; }
        public string dateofbirth { get; set; }
        public string address { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}
