//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankmanagementmainapplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD
    {
        public int sno { get; set; }
        public Nullable<decimal> Account_no { get; set; }
        public string Mode { get; set; }
        public string Rupees { get; set; }
        public Nullable<int> period { get; set; }
        public Nullable<decimal> intrest { get; set; }
        public string maturity_date { get; set; }
        public Nullable<decimal> maturity_amount { get; set; }
        public string start_date { get; set; }
    }
}
