//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankmanagementmainapplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class userAccount
    {
        public decimal Account_no { get; set; }
        public string Name { get; set; }
        public string Dob { get; set; }
        public string Phoneno { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public string state { get; set; }
        public byte[] picture { get; set; }
        public string Gender { get; set; }
        public string m_status { get; set; }
        public string mothername { get; set; }
        public string fathername { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string Date { get; set; }
    }
}
